/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.adjusttesting;

import org.appcelerator.kroll.KrollObject;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.kroll.runtime.v8.V8Function;

import com.adjust.testlibrary.IOnExitListener;

import android.content.Context;

public class OnExitListener implements IOnExitListener {
    private V8Function mJsOnExitListener;
    private KrollObject mKrollObject;

    public OnExitListener(KrollObject krollObject, V8Function jsOnExitListener) {
        mKrollObject = krollObject;
        mJsOnExitListener = jsOnExitListener;
    }

    @Override
    public void onExit() {
		Object[] answer = { };
    	mJsOnExitListener.call(mKrollObject, answer);
    }
}
